def code_to_lang(lang_code):
    if lang_code == "abk": return "Abkhazian"
    elif lang_code == "ace": return "Achinese"
    elif lang_code == "ach": return "Acoli"
    elif lang_code == "ada": return "Adangme"
    elif lang_code == "aar": return "Afar"
    elif lang_code == "afh": return "Afrihili"
    elif lang_code == "afr": return "Afrikaans"
    elif lang_code == "afa": return "Afro-Asiatic (Other)"
    elif lang_code == "aka": return "Akan"
    elif lang_code == "akk": return "Akkadian"
    elif lang_code == "alb": return "Albanian"
    elif lang_code == "sqi": return "Albanian"
    elif lang_code == "ale": return "Aleut"
    elif lang_code == "alg": return "Algonquian languages"
    elif lang_code == "tut": return "Altaic (Other)"
    elif lang_code == "amh": return "Amharic"
    elif lang_code == "apa": return "Apache languages"
    elif lang_code == "ara": return "Arabic"
    elif lang_code == "arc": return "Aramaic"
    elif lang_code == "arp": return "Arapaho"
    elif lang_code == "arn": return "Araucanian"
    elif lang_code == "arw": return "Arawak"
    elif lang_code == "arm": return "Armenian"
    elif lang_code == "hye": return "Armenian"
    elif lang_code == "art": return "Artificial (Other)"
    elif lang_code == "asm": return "Assamese"
    elif lang_code == "ath": return "Athapascan languages"
    elif lang_code == "aus": return "Australian languages"
    elif lang_code == "map": return "Austronesian (Other)"
    elif lang_code == "ava": return "Avaric"
    elif lang_code == "ave": return "Avestan"
    elif lang_code == "awa": return "Awadhi"
    elif lang_code == "aym": return "Aymara"
    elif lang_code == "aze": return "Azerbaijani"
    elif lang_code == "ban": return "Balinese"
    elif lang_code == "bat": return "Baltic (Other)"
    elif lang_code == "bal": return "Baluchi"
    elif lang_code == "bam": return "Bambara"
    elif lang_code == "bai": return "Bamileke languages"
    elif lang_code == "bad": return "Banda"
    elif lang_code == "bnt": return "Bantu (Other)"
    elif lang_code == "bas": return "Basa"
    elif lang_code == "bak": return "Bashkir"
    elif lang_code == "baq": return "Basque"
    elif lang_code == "eus": return "Basque"
    elif lang_code == "btk": return "Batak (Indonesia)"
    elif lang_code == "bej": return "Beja"
    elif lang_code == "bel": return "Belarusian"
    elif lang_code == "bem": return "Bemba"
    elif lang_code == "ben": return "Bengali"
    elif lang_code == "ber": return "Berber (Other)"
    elif lang_code == "bho": return "Bhojpuri"
    elif lang_code == "bih": return "Bihari"
    elif lang_code == "bik": return "Bikol"
    elif lang_code == "bin": return "Bini"
    elif lang_code == "bis": return "Bislama"
    elif lang_code == "bos": return "Bosnian"
    elif lang_code == "bra": return "Braj"
    elif lang_code == "bre": return "Breton"
    elif lang_code == "bug": return "Buginese"
    elif lang_code == "bul": return "Bulgarian"
    elif lang_code == "bua": return "Buriat"
    elif lang_code == "bur": return "Burmese"
    elif lang_code == "mya": return "Burmese"
    elif lang_code == "cad": return "Caddo"
    elif lang_code == "car": return "Carib"
    elif lang_code == "cat": return "Catalan"
    elif lang_code == "cau": return "Caucasian (Other)"
    elif lang_code == "ceb": return "Cebuano"
    elif lang_code == "cel": return "Celtic (Other)"
    elif lang_code == "cai": return "Central American Indian (Other)"
    elif lang_code == "chg": return "Chagatai"
    elif lang_code == "cmc": return "Chamic languages"
    elif lang_code == "cha": return "Chamorro"
    elif lang_code == "che": return "Chechen"
    elif lang_code == "chr": return "Cherokee"
    elif lang_code == "chy": return "Cheyenne"
    elif lang_code == "chb": return "Chibcha"
    elif lang_code == "chi": return "Chinese"
    elif lang_code == "zho": return "Chinese"
    elif lang_code == "chn": return "Chinook jargon"
    elif lang_code == "chp": return "Chipewyan"
    elif lang_code == "cho": return "Choctaw"
    elif lang_code == "chu": return "Church Slavic"
    elif lang_code == "chk": return "Chuukese"
    elif lang_code == "chv": return "Chuvash"
    elif lang_code == "cop": return "Coptic"
    elif lang_code == "cor": return "Cornish"
    elif lang_code == "cos": return "Corsican"
    elif lang_code == "cre": return "Cree"
    elif lang_code == "mus": return "Creek"
    elif lang_code == "crp": return "Creoles and pidgins (Other)"
    elif lang_code == "cpe": return "Creoles and pidgins,"
    elif lang_code == "cpf": return "Creoles and pidgins,"
    elif lang_code == "cpp": return "Creoles and pidgins,"
    elif lang_code == "scr": return "Croatian"
    elif lang_code == "hrv": return "Croatian"
    elif lang_code == "cus": return "Cushitic (Other)"
    elif lang_code == "cze": return "Czech"
    elif lang_code == "ces": return "Czech"
    elif lang_code == "dak": return "Dakota"
    elif lang_code == "dan": return "Danish"
    elif lang_code == "day": return "Dayak"
    elif lang_code == "del": return "Delaware"
    elif lang_code == "din": return "Dinka"
    elif lang_code == "div": return "Divehi"
    elif lang_code == "doi": return "Dogri"
    elif lang_code == "dgr": return "Dogrib"
    elif lang_code == "dra": return "Dravidian (Other)"
    elif lang_code == "dua": return "Duala"
    elif lang_code == "dut": return "Dutch"
    elif lang_code == "nld": return "Dutch"
    elif lang_code == "dum": return "Dutch, Middle (ca. 1050-1350)"
    elif lang_code == "dyu": return "Dyula"
    elif lang_code == "dzo": return "Dzongkha"
    elif lang_code == "efi": return "Efik"
    elif lang_code == "egy": return "Egyptian (Ancient)"
    elif lang_code == "eka": return "Ekajuk"
    elif lang_code == "elx": return "Elamite"
    elif lang_code == "eng": return "English"
    elif lang_code == "enm": return "English, Middle (1100-1500)"
    elif lang_code == "ang": return "English, Old (ca.450-1100)"
    elif lang_code == "epo": return "Esperanto"
    elif lang_code == "est": return "Estonian"
    elif lang_code == "ewe": return "Ewe"
    elif lang_code == "ewo": return "Ewondo"
    elif lang_code == "fan": return "Fang"
    elif lang_code == "fat": return "Fanti"
    elif lang_code == "fao": return "Faroese"
    elif lang_code == "fij": return "Fijian"
    elif lang_code == "fin": return "Finnish"
    elif lang_code == "fiu": return "Finno-Ugrian (Other)"
    elif lang_code == "fon": return "Fon"
    elif lang_code == "fre": return "French"
    elif lang_code == "fra": return "French"
    elif lang_code == "frm": return "French, Middle (ca.1400-1600)"
    elif lang_code == "fro": return "French, Old (842-ca.1400)"
    elif lang_code == "fry": return "Frisian"
    elif lang_code == "fur": return "Friulian"
    elif lang_code == "ful": return "Fulah"
    elif lang_code == "gaa": return "Ga"
    elif lang_code == "glg": return "Gallegan"
    elif lang_code == "lug": return "Ganda"
    elif lang_code == "gay": return "Gayo"
    elif lang_code == "gba": return "Gbaya"
    elif lang_code == "gez": return "Geez"
    elif lang_code == "geo": return "Georgian"
    elif lang_code == "kat": return "Georgian"
    elif lang_code == "ger": return "German"
    elif lang_code == "deu": return "German"
    elif lang_code == "nds": return "Saxon"
    elif lang_code == "gmh": return "German, Middle High (ca.1050-1500)"
    elif lang_code == "goh": return "German, Old High (ca.750-1050)"
    elif lang_code == "gem": return "Germanic (Other)"
    elif lang_code == "gil": return "Gilbertese"
    elif lang_code == "gon": return "Gondi"
    elif lang_code == "gor": return "Gorontalo"
    elif lang_code == "got": return "Gothic"
    elif lang_code == "grb": return "Grebo"
    elif lang_code == "grc": return "Greek, Ancient (to 1453)"
    elif lang_code == "gre": return "Greek"
    elif lang_code == "ell": return "Greek"
    elif lang_code == "grn": return "Guarani"
    elif lang_code == "guj": return "Gujarati"
    elif lang_code == "gwi": return "Gwich´in"
    elif lang_code == "hai": return "Haida"
    elif lang_code == "hau": return "Hausa"
    elif lang_code == "haw": return "Hawaiian"
    elif lang_code == "heb": return "Hebrew"
    elif lang_code == "her": return "Herero"
    elif lang_code == "hil": return "Hiligaynon"
    elif lang_code == "him": return "Himachali"
    elif lang_code == "hin": return "Hindi"
    elif lang_code == "hmo": return "Hiri Motu"
    elif lang_code == "hit": return "Hittite"
    elif lang_code == "hmn": return "Hmong"
    elif lang_code == "hun": return "Hungarian"
    elif lang_code == "hup": return "Hupa"
    elif lang_code == "iba": return "Iban"
    elif lang_code == "ice": return "Icelandic"
    elif lang_code == "isl": return "Icelandic"
    elif lang_code == "ibo": return "Igbo"
    elif lang_code == "ijo": return "Ijo"
    elif lang_code == "ilo": return "Iloko"
    elif lang_code == "inc": return "Indic (Other)"
    elif lang_code == "ine": return "Indo-European (Other)"
    elif lang_code == "ind": return "Indonesian"
    elif lang_code == "ina": return "Interlingua (International"
    elif lang_code == "ile": return "Interlingue"
    elif lang_code == "iku": return "Inuktitut"
    elif lang_code == "ipk": return "Inupiaq"
    elif lang_code == "ira": return "Iranian (Other)"
    elif lang_code == "gle": return "Irish"
    elif lang_code == "mga": return "Irish, Middle (900-1200)"
    elif lang_code == "sga": return "Irish, Old (to 900)"
    elif lang_code == "iro": return "Iroquoian languages"
    elif lang_code == "ita": return "Italian"
    elif lang_code == "jpn": return "Japanese"
    elif lang_code == "jav": return "Javanese"
    elif lang_code == "jrb": return "Judeo-Arabic"
    elif lang_code == "jpr": return "Judeo-Persian"
    elif lang_code == "kab": return "Kabyle"
    elif lang_code == "kac": return "Kachin"
    elif lang_code == "kal": return "Kalaallisut"
    elif lang_code == "kam": return "Kamba"
    elif lang_code == "kan": return "Kannada"
    elif lang_code == "kau": return "Kanuri"
    elif lang_code == "kaa": return "Kara-Kalpak"
    elif lang_code == "kar": return "Karen"
    elif lang_code == "kas": return "Kashmiri"
    elif lang_code == "kaw": return "Kawi"
    elif lang_code == "kaz": return "Kazakh"
    elif lang_code == "kha": return "Khasi"
    elif lang_code == "khm": return "Khmer"
    elif lang_code == "khi": return "Khoisan (Other)"
    elif lang_code == "kho": return "Khotanese"
    elif lang_code == "kik": return "Kikuyu"
    elif lang_code == "kmb": return "Kimbundu"
    elif lang_code == "kin": return "Kinyarwanda"
    elif lang_code == "kir": return "Kirghiz"
    elif lang_code == "kom": return "Komi"
    elif lang_code == "kon": return "Kongo"
    elif lang_code == "kok": return "Konkani"
    elif lang_code == "kor": return "Korean"
    elif lang_code == "kos": return "Kosraean"
    elif lang_code == "kpe": return "Kpelle"
    elif lang_code == "kro": return "Kru"
    elif lang_code == "kua": return "Kuanyama"
    elif lang_code == "kum": return "Kumyk"
    elif lang_code == "kur": return "Kurdish"
    elif lang_code == "kru": return "Kurukh"
    elif lang_code == "kut": return "Kutenai"
    elif lang_code == "lad": return "Ladino"
    elif lang_code == "lah": return "Lahnda"
    elif lang_code == "lam": return "Lamba"
    elif lang_code == "lao": return "Lao"
    elif lang_code == "lat": return "Latin"
    elif lang_code == "lav": return "Latvian"
    elif lang_code == "ltz": return "Letzeburgesch"
    elif lang_code == "lez": return "Lezghian"
    elif lang_code == "lin": return "Lingala"
    elif lang_code == "lit": return "Lithuanian"
    elif lang_code == "loz": return "Lozi"
    elif lang_code == "lub": return "Luba-Katanga"
    elif lang_code == "lua": return "Luba-Lulua"
    elif lang_code == "lui": return "Luiseno"
    elif lang_code == "lun": return "Lunda"
    elif lang_code == "luo": return "Luo (Kenya and Tanzania)"
    elif lang_code == "lus": return "Lushai"
    elif lang_code == "mac": return "Macedonian"
    elif lang_code == "mkd": return "Macedonian"
    elif lang_code == "mad": return "Madurese"
    elif lang_code == "mag": return "Magahi"
    elif lang_code == "mai": return "Maithili"
    elif lang_code == "mak": return "Makasar"
    elif lang_code == "mlg": return "Malagasy"
    elif lang_code == "may": return "Malay"
    elif lang_code == "msa": return "Malay"
    elif lang_code == "mal": return "Malayalam"
    elif lang_code == "mlt": return "Maltese"
    elif lang_code == "mnc": return "Manchu"
    elif lang_code == "mdr": return "Mandar"
    elif lang_code == "man": return "Mandingo"
    elif lang_code == "mni": return "Manipuri"
    elif lang_code == "mno": return "Manobo languages"
    elif lang_code == "glv": return "Manx"
    elif lang_code == "mao": return "Maori"
    elif lang_code == "mri": return "Maori"
    elif lang_code == "mar": return "Marathi"
    elif lang_code == "chm": return "Mari"
    elif lang_code == "mah": return "Marshall"
    elif lang_code == "mwr": return "Marwari"
    elif lang_code == "mas": return "Masai"
    elif lang_code == "myn": return "Mayan languages"
    elif lang_code == "men": return "Mende"
    elif lang_code == "mic": return "Micmac"
    elif lang_code == "min": return "Minangkabau"
    elif lang_code == "mis": return "Miscellaneous languages"
    elif lang_code == "moh": return "Mohawk"
    elif lang_code == "mol": return "Moldavian"
    elif lang_code == "mkh": return "Mon-Khmer (Other)"
    elif lang_code == "lol": return "Mongo"
    elif lang_code == "mon": return "Mongolian"
    elif lang_code == "mos": return "Mossi"
    elif lang_code == "mul": return "Multiple languages"
    elif lang_code == "mun": return "Munda languages"
    elif lang_code == "nah": return "Nahuatl"
    elif lang_code == "nau": return "Nauru"
    elif lang_code == "nav": return "Navajo"
    elif lang_code == "nde": return "Ndebele, North"
    elif lang_code == "nbl": return "Ndebele, South"
    elif lang_code == "ndo": return "Ndonga"
    elif lang_code == "nep": return "Nepali"
    elif lang_code == "new": return "Newari"
    elif lang_code == "nia": return "Nias"
    elif lang_code == "nic": return "Niger-Kordofanian (Other)"
    elif lang_code == "ssa": return "Nilo-Saharan (Other)"
    elif lang_code == "niu": return "Niuean"
    elif lang_code == "non": return "Norse, Old"
    elif lang_code == "nai": return "North American Indian (Other)"
    elif lang_code == "sme": return "Northern Sami"
    elif lang_code == "nor": return "Norwegian"
    elif lang_code == "nob": return "Norwegian Bokmål"
    elif lang_code == "nno": return "Norwegian Nynorsk"
    elif lang_code == "nub": return "Nubian languages"
    elif lang_code == "nym": return "Nyamwezi"
    elif lang_code == "nya": return "Nyanja"
    elif lang_code == "nyn": return "Nyankole"
    elif lang_code == "nyo": return "Nyoro"
    elif lang_code == "nzi": return "Nzima"
    elif lang_code == "oci": return "Occitan"
    elif lang_code == "oji": return "Ojibwa"
    elif lang_code == "ori": return "Oriya"
    elif lang_code == "orm": return "Oromo"
    elif lang_code == "osa": return "Osage"
    elif lang_code == "oss": return "Ossetian"
    elif lang_code == "oto": return "Otomian languages"
    elif lang_code == "pal": return "Pahlavi"
    elif lang_code == "pau": return "Palauan"
    elif lang_code == "pli": return "Pali"
    elif lang_code == "pam": return "Pampanga"
    elif lang_code == "pag": return "Pangasinan"
    elif lang_code == "pan": return "Panjabi"
    elif lang_code == "pap": return "Papiamento"
    elif lang_code == "paa": return "Papuan (Other)"
    elif lang_code == "per": return "Persian"
    elif lang_code == "fas": return "Persian"
    elif lang_code == "peo": return "Persian, Old (ca.600-400 B.C.)"
    elif lang_code == "phi": return "Philippine (Other)"
    elif lang_code == "phn": return "Phoenician"
    elif lang_code == "pon": return "Pohnpeian"
    elif lang_code == "pol": return "Polish"
    elif lang_code == "por": return "Portuguese"
    elif lang_code == "pra": return "Prakrit languages"
    elif lang_code == "pro": return "Provençal"
    elif lang_code == "pus": return "Pushto"
    elif lang_code == "que": return "Quechua"
    elif lang_code == "roh": return "Raeto-Romance"
    elif lang_code == "raj": return "Rajasthani"
    elif lang_code == "rap": return "Rapanui"
    elif lang_code == "rar": return "Rarotongan"
    elif lang_code == "roa": return "Romance (Other)"
    elif lang_code == "rum": return "Romanian"
    elif lang_code == "ron": return "Romanian"
    elif lang_code == "rom": return "Romany"
    elif lang_code == "run": return "Rundi"
    elif lang_code == "rus": return "Russian"
    elif lang_code == "sal": return "Salishan languages"
    elif lang_code == "sam": return "Samaritan Aramaic"
    elif lang_code == "smi": return "Sami languages (Other)"
    elif lang_code == "smo": return "Samoan"
    elif lang_code == "sad": return "Sandawe"
    elif lang_code == "sag": return "Sango"
    elif lang_code == "san": return "Sanskrit"
    elif lang_code == "sat": return "Santali"
    elif lang_code == "srd": return "Sardinian"
    elif lang_code == "sas": return "Sasak"
    elif lang_code == "sco": return "Scots"
    elif lang_code == "gla": return "Gaelic"
    elif lang_code == "sel": return "Selkup"
    elif lang_code == "sem": return "Semitic (Other)"
    elif lang_code == "scc": return "Serbian"
    elif lang_code == "srp": return "Serbian"
    elif lang_code == "srr": return "Serer"
    elif lang_code == "shn": return "Shan"
    elif lang_code == "sna": return "Shona"
    elif lang_code == "sid": return "Sidamo"
    elif lang_code == "sgn": return "Sign languages"
    elif lang_code == "bla": return "Siksika"
    elif lang_code == "snd": return "Sindhi"
    elif lang_code == "sin": return "Sinhalese"
    elif lang_code == "sit": return "Sino-Tibetan (Other)"
    elif lang_code == "sio": return "Siouan languages"
    elif lang_code == "den": return "Slave (Athapascan)"
    elif lang_code == "sla": return "Slavic (Other)"
    elif lang_code == "slo": return "Slovak"
    elif lang_code == "slk": return "Slovak"
    elif lang_code == "slv": return "Slovenian"
    elif lang_code == "sog": return "Sogdian"
    elif lang_code == "som": return "Somali"
    elif lang_code == "son": return "Songhai"
    elif lang_code == "snk": return "Soninke"
    elif lang_code == "wen": return "Sorbian languages"
    elif lang_code == "nso": return "Sotho, Northern"
    elif lang_code == "sot": return "Sotho, Southern"
    elif lang_code == "sai": return "South American Indian (Other)"
    elif lang_code == "spa": return "Spanish"
    elif lang_code == "suk": return "Sukuma"
    elif lang_code == "sux": return "Sumerian"
    elif lang_code == "sun": return "Sundanese"
    elif lang_code == "sus": return "Susu"
    elif lang_code == "swa": return "Swahili"
    elif lang_code == "ssw": return "Swati"
    elif lang_code == "swe": return "Swedish"
    elif lang_code == "syr": return "Syriac"
    elif lang_code == "tgl": return "Tagalog"
    elif lang_code == "tah": return "Tahitian"
    elif lang_code == "tai": return "Tai (Other)"
    elif lang_code == "tgk": return "Tajik"
    elif lang_code == "tmh": return "Tamashek"
    elif lang_code == "tam": return "Tamil"
    elif lang_code == "tat": return "Tatar"
    elif lang_code == "tel": return "Telugu"
    elif lang_code == "ter": return "Tereno"
    elif lang_code == "tet": return "Tetum"
    elif lang_code == "tha": return "Thai"
    elif lang_code == "tib": return "Tibetan"
    elif lang_code == "bod": return "Tibetan"
    elif lang_code == "tig": return "Tigre"
    elif lang_code == "tir": return "Tigrinya"
    elif lang_code == "tem": return "Timne"
    elif lang_code == "tiv": return "Tiv"
    elif lang_code == "tli": return "Tlingit"
    elif lang_code == "tpi": return "Tok Pisin"
    elif lang_code == "tkl": return "Tokelau"
    elif lang_code == "tog": return "Tonga (Nyasa)"
    elif lang_code == "ton": return "Tonga (Tonga Islands)"
    elif lang_code == "tsi": return "Tsimshian"
    elif lang_code == "tso": return "Tsonga"
    elif lang_code == "tsn": return "Tswana"
    elif lang_code == "tum": return "Tumbuka"
    elif lang_code == "tur": return "Turkish"
    elif lang_code == "ota": return "Turkish, Ottoman (1500-1928)"
    elif lang_code == "tuk": return "Turkmen"
    elif lang_code == "tvl": return "Tuvalu"
    elif lang_code == "tyv": return "Tuvinian"
    elif lang_code == "twi": return "Twi"
    elif lang_code == "uga": return "Ugaritic"
    elif lang_code == "uig": return "Uighur"
    elif lang_code == "ukr": return "Ukrainian"
    elif lang_code == "umb": return "Umbundu"
    elif lang_code == "und": return "Undetermined"
    elif lang_code == "urd": return "Urdu"
    elif lang_code == "uzb": return "Uzbek"
    elif lang_code == "vai": return "Vai"
    elif lang_code == "ven": return "Venda"
    elif lang_code == "vie": return "Vietnamese"
    elif lang_code == "vol": return "Volapük"
    elif lang_code == "vot": return "Votic"
    elif lang_code == "wak": return "Wakashan languages"
    elif lang_code == "wal": return "Walamo"
    elif lang_code == "war": return "Waray"
    elif lang_code == "was": return "Washo"
    elif lang_code == "wel": return "Welsh"
    elif lang_code == "cym": return "Welsh"
    elif lang_code == "wol": return "Wolof"
    elif lang_code == "xho": return "Xhosa"
    elif lang_code == "sah": return "Yakut"
    elif lang_code == "yao": return "Yao"
    elif lang_code == "yap": return "Yapese"
    elif lang_code == "yid": return "Yiddish"
    elif lang_code == "yor": return "Yoruba"
    elif lang_code == "ypk": return "Yupik languages"
    elif lang_code == "znd": return "Zande"
    elif lang_code == "zap": return "Zapotec"
    elif lang_code == "zen": return "Zenaga"
    elif lang_code == "zha": return "Zhuang"
    elif lang_code == "zul": return "Zulu"
    elif lang_code == "zun": return "Zuni"
    else: return "und"

def lang_to_code(lang_name):
    if lang_name == "Abkhazian" : return "abk"
    elif lang_name == "Achinese": return "ace"
    elif lang_name == "Acoli" : return "ach"
    elif lang_name == "Adangme" : return "ada"
    elif lang_name == "Afar": return "aar"
    elif lang_name == "Afrihili": return "afh"
    elif lang_name == "Afrikaans" : return "afr"
    elif lang_name == "Afro-Asiatic (Other)": return "afa"
    elif lang_name == "Akan": return "aka"
    elif lang_name == "Akkadian": return "akk"
    elif lang_name == "Albanian": return "alb"
    elif lang_name == "Albanian": return "sqi"
    elif lang_name == "Aleut" : return "ale"
    elif lang_name == "Algonquian languages": return "alg"
    elif lang_name == "Altaic (Other)": return "tut"
    elif lang_name == "Amharic" : return "amh"
    elif lang_name == "Apache languages": return "apa"
    elif lang_name == "Arabic": return "ara"
    elif lang_name == "Aramaic" : return "arc"
    elif lang_name == "Arapaho" : return "arp"
    elif lang_name == "Araucanian": return "arn"
    elif lang_name == "Arawak": return "arw"
    elif lang_name == "Armenian": return "arm"
    elif lang_name == "Armenian": return "hye"
    elif lang_name == "Artificial (Other)": return "art"
    elif lang_name == "Assamese": return "asm"
    elif lang_name == "Athapascan languages": return "ath"
    elif lang_name == "Australian languages": return "aus"
    elif lang_name == "Austronesian (Other)": return "map"
    elif lang_name == "Avaric": return "ava"
    elif lang_name == "Avestan" : return "ave"
    elif lang_name == "Awadhi": return "awa"
    elif lang_name == "Aymara": return "aym"
    elif lang_name == "Azerbaijani" : return "aze"
    elif lang_name == "Balinese": return "ban"
    elif lang_name == "Baltic (Other)": return "bat"
    elif lang_name == "Baluchi" : return "bal"
    elif lang_name == "Bambara" : return "bam"
    elif lang_name == "Bamileke languages": return "bai"
    elif lang_name == "Banda" : return "bad"
    elif lang_name == "Bantu (Other)" : return "bnt"
    elif lang_name == "Basa": return "bas"
    elif lang_name == "Bashkir" : return "bak"
    elif lang_name == "Basque": return "baq"
    elif lang_name == "Basque": return "eus"
    elif lang_name == "Batak (Indonesia)" : return "btk"
    elif lang_name == "Beja": return "bej"
    elif lang_name == "Belarusian": return "bel"
    elif lang_name == "Bemba" : return "bem"
    elif lang_name == "Bengali" : return "ben"
    elif lang_name == "Berber (Other)": return "ber"
    elif lang_name == "Bhojpuri": return "bho"
    elif lang_name == "Bihari": return "bih"
    elif lang_name == "Bikol" : return "bik"
    elif lang_name == "Bini": return "bin"
    elif lang_name == "Bislama" : return "bis"
    elif lang_name == "Bosnian" : return "bos"
    elif lang_name == "Braj": return "bra"
    elif lang_name == "Breton": return "bre"
    elif lang_name == "Buginese": return "bug"
    elif lang_name == "Bulgarian" : return "bul"
    elif lang_name == "Buriat": return "bua"
    elif lang_name == "Burmese" : return "bur"
    elif lang_name == "Burmese" : return "mya"
    elif lang_name == "Caddo" : return "cad"
    elif lang_name == "Carib" : return "car"
    elif lang_name == "Catalan" : return "cat"
    elif lang_name == "Caucasian (Other)" : return "cau"
    elif lang_name == "Cebuano" : return "ceb"
    elif lang_name == "Celtic (Other)": return "cel"
    elif lang_name == "Central American Indian (Other)" : return "cai"
    elif lang_name == "Chagatai": return "chg"
    elif lang_name == "Chamic languages": return "cmc"
    elif lang_name == "Chamorro": return "cha"
    elif lang_name == "Chechen" : return "che"
    elif lang_name == "Cherokee": return "chr"
    elif lang_name == "Cheyenne": return "chy"
    elif lang_name == "Chibcha" : return "chb"
    elif lang_name == "Chinese" : return "chi"
    elif lang_name == "Chinese" : return "zho"
    elif lang_name == "Chinook jargon": return "chn"
    elif lang_name == "Chipewyan" : return "chp"
    elif lang_name == "Choctaw" : return "cho"
    elif lang_name == "Church Slavic" : return "chu"
    elif lang_name == "Chuukese": return "chk"
    elif lang_name == "Chuvash" : return "chv"
    elif lang_name == "Coptic": return "cop"
    elif lang_name == "Cornish" : return "cor"
    elif lang_name == "Corsican": return "cos"
    elif lang_name == "Cree": return "cre"
    elif lang_name == "Creek" : return "mus"
    elif lang_name == "Creoles and pidgins (Other)" : return "crp"
    elif lang_name == "Creoles and pidgins,": return "cpe"
    elif lang_name == "Creoles and pidgins,": return "cpf"
    elif lang_name == "Creoles and pidgins,": return "cpp"
    elif lang_name == "Croatian": return "scr"
    elif lang_name == "Croatian": return "hrv"
    elif lang_name == "Cushitic (Other)": return "cus"
    elif lang_name == "Czech" : return "cze"
    elif lang_name == "Czech" : return "ces"
    elif lang_name == "Dakota": return "dak"
    elif lang_name == "Danish": return "dan"
    elif lang_name == "Dayak" : return "day"
    elif lang_name == "Delaware": return "del"
    elif lang_name == "Dinka" : return "din"
    elif lang_name == "Divehi": return "div"
    elif lang_name == "Dogri" : return "doi"
    elif lang_name == "Dogrib": return "dgr"
    elif lang_name == "Dravidian (Other)" : return "dra"
    elif lang_name == "Duala" : return "dua"
    elif lang_name == "Dutch" : return "dut"
    elif lang_name == "Dutch" : return "nld"
    elif lang_name == "Dutch, Middle (ca. 1050-1350)" : return "dum"
    elif lang_name == "Dyula" : return "dyu"
    elif lang_name == "Dzongkha": return "dzo"
    elif lang_name == "Efik": return "efi"
    elif lang_name == "Egyptian (Ancient)": return "egy"
    elif lang_name == "Ekajuk": return "eka"
    elif lang_name == "Elamite" : return "elx"
    elif lang_name == "English" : return "eng"
    elif lang_name == "English, Middle (1100-1500)" : return "enm"
    elif lang_name == "English, Old (ca.450-1100)": return "ang"
    elif lang_name == "Esperanto" : return "epo"
    elif lang_name == "Estonian": return "est"
    elif lang_name == "Ewe" : return "ewe"
    elif lang_name == "Ewondo": return "ewo"
    elif lang_name == "Fang": return "fan"
    elif lang_name == "Fanti" : return "fat"
    elif lang_name == "Faroese" : return "fao"
    elif lang_name == "Fijian": return "fij"
    elif lang_name == "Finnish" : return "fin"
    elif lang_name == "Finno-Ugrian (Other)": return "fiu"
    elif lang_name == "Fon" : return "fon"
    elif lang_name == "French": return "fre"
    elif lang_name == "French": return "fra"
    elif lang_name == "French, Middle (ca.1400-1600)" : return "frm"
    elif lang_name == "French, Old (842-ca.1400)" : return "fro"
    elif lang_name == "Frisian" : return "fry"
    elif lang_name == "Friulian": return "fur"
    elif lang_name == "Fulah" : return "ful"
    elif lang_name == "Ga": return "gaa"
    elif lang_name == "Gallegan": return "glg"
    elif lang_name == "Ganda" : return "lug"
    elif lang_name == "Gayo": return "gay"
    elif lang_name == "Gbaya" : return "gba"
    elif lang_name == "Geez": return "gez"
    elif lang_name == "Georgian": return "geo"
    elif lang_name == "Georgian": return "kat"
    elif lang_name == "German": return "ger"
    elif lang_name == "German": return "deu"
    elif lang_name == "Saxon" : return "nds"
    elif lang_name == "German, Middle High (ca.1050-1500)": return "gmh"
    elif lang_name == "German, Old High (ca.750-1050)": return "goh"
    elif lang_name == "Germanic (Other)": return "gem"
    elif lang_name == "Gilbertese": return "gil"
    elif lang_name == "Gondi" : return "gon"
    elif lang_name == "Gorontalo" : return "gor"
    elif lang_name == "Gothic": return "got"
    elif lang_name == "Grebo" : return "grb"
    elif lang_name == "Greek, Ancient (to 1453)": return "grc"
    elif lang_name == "Greek" : return "gre"
    elif lang_name == "Greek" : return "ell"
    elif lang_name == "Guarani" : return "grn"
    elif lang_name == "Gujarati": return "guj"
    elif lang_name == "Gwich´in": return "gwi"
    elif lang_name == "Haida" : return "hai"
    elif lang_name == "Hausa" : return "hau"
    elif lang_name == "Hawaiian": return "haw"
    elif lang_name == "Hebrew": return "heb"
    elif lang_name == "Herero": return "her"
    elif lang_name == "Hiligaynon": return "hil"
    elif lang_name == "Himachali" : return "him"
    elif lang_name == "Hindi" : return "hin"
    elif lang_name == "Hiri Motu" : return "hmo"
    elif lang_name == "Hittite" : return "hit"
    elif lang_name == "Hmong" : return "hmn"
    elif lang_name == "Hungarian" : return "hun"
    elif lang_name == "Hupa": return "hup"
    elif lang_name == "Iban": return "iba"
    elif lang_name == "Icelandic" : return "ice"
    elif lang_name == "Icelandic" : return "isl"
    elif lang_name == "Igbo": return "ibo"
    elif lang_name == "Ijo" : return "ijo"
    elif lang_name == "Iloko" : return "ilo"
    elif lang_name == "Indic (Other)" : return "inc"
    elif lang_name == "Indo-European (Other)" : return "ine"
    elif lang_name == "Indonesian": return "ind"
    elif lang_name == "Interlingua (International": return "ina"
    elif lang_name == "Interlingue" : return "ile"
    elif lang_name == "Inuktitut" : return "iku"
    elif lang_name == "Inupiaq" : return "ipk"
    elif lang_name == "Iranian (Other)" : return "ira"
    elif lang_name == "Irish" : return "gle"
    elif lang_name == "Irish, Middle (900-1200)": return "mga"
    elif lang_name == "Irish, Old (to 900)" : return "sga"
    elif lang_name == "Iroquoian languages" : return "iro"
    elif lang_name == "Italian" : return "ita"
    elif lang_name == "Japanese": return "jpn"
    elif lang_name == "Javanese": return "jav"
    elif lang_name == "Judeo-Arabic": return "jrb"
    elif lang_name == "Judeo-Persian" : return "jpr"
    elif lang_name == "Kabyle": return "kab"
    elif lang_name == "Kachin": return "kac"
    elif lang_name == "Kalaallisut" : return "kal"
    elif lang_name == "Kamba" : return "kam"
    elif lang_name == "Kannada" : return "kan"
    elif lang_name == "Kanuri": return "kau"
    elif lang_name == "Kara-Kalpak" : return "kaa"
    elif lang_name == "Karen" : return "kar"
    elif lang_name == "Kashmiri": return "kas"
    elif lang_name == "Kawi": return "kaw"
    elif lang_name == "Kazakh": return "kaz"
    elif lang_name == "Khasi" : return "kha"
    elif lang_name == "Khmer" : return "khm"
    elif lang_name == "Khoisan (Other)" : return "khi"
    elif lang_name == "Khotanese" : return "kho"
    elif lang_name == "Kikuyu": return "kik"
    elif lang_name == "Kimbundu": return "kmb"
    elif lang_name == "Kinyarwanda" : return "kin"
    elif lang_name == "Kirghiz" : return "kir"
    elif lang_name == "Komi": return "kom"
    elif lang_name == "Kongo" : return "kon"
    elif lang_name == "Konkani" : return "kok"
    elif lang_name == "Korean": return "kor"
    elif lang_name == "Kosraean": return "kos"
    elif lang_name == "Kpelle": return "kpe"
    elif lang_name == "Kru" : return "kro"
    elif lang_name == "Kuanyama": return "kua"
    elif lang_name == "Kumyk" : return "kum"
    elif lang_name == "Kurdish" : return "kur"
    elif lang_name == "Kurukh": return "kru"
    elif lang_name == "Kutenai" : return "kut"
    elif lang_name == "Ladino": return "lad"
    elif lang_name == "Lahnda": return "lah"
    elif lang_name == "Lamba" : return "lam"
    elif lang_name == "Lao" : return "lao"
    elif lang_name == "Latin" : return "lat"
    elif lang_name == "Latvian" : return "lav"
    elif lang_name == "Letzeburgesch" : return "ltz"
    elif lang_name == "Lezghian": return "lez"
    elif lang_name == "Lingala" : return "lin"
    elif lang_name == "Lithuanian": return "lit"
    elif lang_name == "Lozi": return "loz"
    elif lang_name == "Luba-Katanga": return "lub"
    elif lang_name == "Luba-Lulua": return "lua"
    elif lang_name == "Luiseno" : return "lui"
    elif lang_name == "Lunda" : return "lun"
    elif lang_name == "Luo (Kenya and Tanzania)": return "luo"
    elif lang_name == "Lushai": return "lus"
    elif lang_name == "Macedonian": return "mac"
    elif lang_name == "Macedonian": return "mkd"
    elif lang_name == "Madurese": return "mad"
    elif lang_name == "Magahi": return "mag"
    elif lang_name == "Maithili": return "mai"
    elif lang_name == "Makasar" : return "mak"
    elif lang_name == "Malagasy": return "mlg"
    elif lang_name == "Malay" : return "may"
    elif lang_name == "Malay" : return "msa"
    elif lang_name == "Malayalam" : return "mal"
    elif lang_name == "Maltese" : return "mlt"
    elif lang_name == "Manchu": return "mnc"
    elif lang_name == "Mandar": return "mdr"
    elif lang_name == "Mandingo": return "man"
    elif lang_name == "Manipuri": return "mni"
    elif lang_name == "Manobo languages": return "mno"
    elif lang_name == "Manx": return "glv"
    elif lang_name == "Maori" : return "mao"
    elif lang_name == "Maori" : return "mri"
    elif lang_name == "Marathi" : return "mar"
    elif lang_name == "Mari": return "chm"
    elif lang_name == "Marshall": return "mah"
    elif lang_name == "Marwari" : return "mwr"
    elif lang_name == "Masai" : return "mas"
    elif lang_name == "Mayan languages" : return "myn"
    elif lang_name == "Mende" : return "men"
    elif lang_name == "Micmac": return "mic"
    elif lang_name == "Minangkabau" : return "min"
    elif lang_name == "Miscellaneous languages" : return "mis"
    elif lang_name == "Mohawk": return "moh"
    elif lang_name == "Moldavian" : return "mol"
    elif lang_name == "Mon-Khmer (Other)" : return "mkh"
    elif lang_name == "Mongo" : return "lol"
    elif lang_name == "Mongolian" : return "mon"
    elif lang_name == "Mossi" : return "mos"
    elif lang_name == "Multiple languages": return "mul"
    elif lang_name == "Munda languages" : return "mun"
    elif lang_name == "Nahuatl" : return "nah"
    elif lang_name == "Nauru" : return "nau"
    elif lang_name == "Navajo": return "nav"
    elif lang_name == "Ndebele, North": return "nde"
    elif lang_name == "Ndebele, South": return "nbl"
    elif lang_name == "Ndonga": return "ndo"
    elif lang_name == "Nepali": return "nep"
    elif lang_name == "Newari": return "new"
    elif lang_name == "Nias": return "nia"
    elif lang_name == "Niger-Kordofanian (Other)" : return "nic"
    elif lang_name == "Nilo-Saharan (Other)": return "ssa"
    elif lang_name == "Niuean": return "niu"
    elif lang_name == "Norse, Old": return "non"
    elif lang_name == "North American Indian (Other)" : return "nai"
    elif lang_name == "Northern Sami" : return "sme"
    elif lang_name == "Norwegian" : return "nor"
    elif lang_name == "Norwegian Bokmål": return "nob"
    elif lang_name == "Norwegian Nynorsk" : return "nno"
    elif lang_name == "Nubian languages": return "nub"
    elif lang_name == "Nyamwezi": return "nym"
    elif lang_name == "Nyanja": return "nya"
    elif lang_name == "Nyankole": return "nyn"
    elif lang_name == "Nyoro" : return "nyo"
    elif lang_name == "Nzima" : return "nzi"
    elif lang_name == "Occitan" : return "oci"
    elif lang_name == "Ojibwa": return "oji"
    elif lang_name == "Oriya" : return "ori"
    elif lang_name == "Oromo" : return "orm"
    elif lang_name == "Osage" : return "osa"
    elif lang_name == "Ossetian": return "oss"
    elif lang_name == "Otomian languages" : return "oto"
    elif lang_name == "Pahlavi" : return "pal"
    elif lang_name == "Palauan" : return "pau"
    elif lang_name == "Pali": return "pli"
    elif lang_name == "Pampanga": return "pam"
    elif lang_name == "Pangasinan": return "pag"
    elif lang_name == "Panjabi" : return "pan"
    elif lang_name == "Papiamento": return "pap"
    elif lang_name == "Papuan (Other)": return "paa"
    elif lang_name == "Persian" : return "per"
    elif lang_name == "Persian" : return "fas"
    elif lang_name == "Persian, Old (ca.600-400 B.C.)": return "peo"
    elif lang_name == "Philippine (Other)": return "phi"
    elif lang_name == "Phoenician": return "phn"
    elif lang_name == "Pohnpeian" : return "pon"
    elif lang_name == "Polish": return "pol"
    elif lang_name == "Portuguese": return "por"
    elif lang_name == "Prakrit languages" : return "pra"
    elif lang_name == "Provençal" : return "pro"
    elif lang_name == "Pushto": return "pus"
    elif lang_name == "Quechua" : return "que"
    elif lang_name == "Raeto-Romance" : return "roh"
    elif lang_name == "Rajasthani": return "raj"
    elif lang_name == "Rapanui" : return "rap"
    elif lang_name == "Rarotongan": return "rar"
    elif lang_name == "Romance (Other)" : return "roa"
    elif lang_name == "Romanian": return "rum"
    elif lang_name == "Romanian": return "ron"
    elif lang_name == "Romany": return "rom"
    elif lang_name == "Rundi" : return "run"
    elif lang_name == "Russian" : return "rus"
    elif lang_name == "Salishan languages": return "sal"
    elif lang_name == "Samaritan Aramaic" : return "sam"
    elif lang_name == "Sami languages (Other)": return "smi"
    elif lang_name == "Samoan": return "smo"
    elif lang_name == "Sandawe" : return "sad"
    elif lang_name == "Sango" : return "sag"
    elif lang_name == "Sanskrit": return "san"
    elif lang_name == "Santali" : return "sat"
    elif lang_name == "Sardinian" : return "srd"
    elif lang_name == "Sasak" : return "sas"
    elif lang_name == "Scots" : return "sco"
    elif lang_name == "Gaelic": return "gla"
    elif lang_name == "Selkup": return "sel"
    elif lang_name == "Semitic (Other)" : return "sem"
    elif lang_name == "Serbian" : return "scc"
    elif lang_name == "Serbian" : return "srp"
    elif lang_name == "Serer" : return "srr"
    elif lang_name == "Shan": return "shn"
    elif lang_name == "Shona" : return "sna"
    elif lang_name == "Sidamo": return "sid"
    elif lang_name == "Sign languages": return "sgn"
    elif lang_name == "Siksika" : return "bla"
    elif lang_name == "Sindhi": return "snd"
    elif lang_name == "Sinhalese" : return "sin"
    elif lang_name == "Sino-Tibetan (Other)": return "sit"
    elif lang_name == "Siouan languages": return "sio"
    elif lang_name == "Slave (Athapascan)": return "den"
    elif lang_name == "Slavic (Other)": return "sla"
    elif lang_name == "Slovak": return "slo"
    elif lang_name == "Slovak": return "slk"
    elif lang_name == "Slovenian" : return "slv"
    elif lang_name == "Sogdian" : return "sog"
    elif lang_name == "Somali": return "som"
    elif lang_name == "Songhai" : return "son"
    elif lang_name == "Soninke" : return "snk"
    elif lang_name == "Sorbian languages" : return "wen"
    elif lang_name == "Sotho, Northern" : return "nso"
    elif lang_name == "Sotho, Southern" : return "sot"
    elif lang_name == "South American Indian (Other)" : return "sai"
    elif lang_name == "Spanish" : return "spa"
    elif lang_name == "Sukuma": return "suk"
    elif lang_name == "Sumerian": return "sux"
    elif lang_name == "Sundanese" : return "sun"
    elif lang_name == "Susu": return "sus"
    elif lang_name == "Swahili" : return "swa"
    elif lang_name == "Swati" : return "ssw"
    elif lang_name == "Swedish" : return "swe"
    elif lang_name == "Syriac": return "syr"
    elif lang_name == "Tagalog" : return "tgl"
    elif lang_name == "Tahitian": return "tah"
    elif lang_name == "Tai (Other)" : return "tai"
    elif lang_name == "Tajik" : return "tgk"
    elif lang_name == "Tamashek": return "tmh"
    elif lang_name == "Tamil" : return "tam"
    elif lang_name == "Tatar" : return "tat"
    elif lang_name == "Telugu": return "tel"
    elif lang_name == "Tereno": return "ter"
    elif lang_name == "Tetum" : return "tet"
    elif lang_name == "Thai": return "tha"
    elif lang_name == "Tibetan" : return "tib"
    elif lang_name == "Tibetan" : return "bod"
    elif lang_name == "Tigre" : return "tig"
    elif lang_name == "Tigrinya": return "tir"
    elif lang_name == "Timne" : return "tem"
    elif lang_name == "Tiv" : return "tiv"
    elif lang_name == "Tlingit" : return "tli"
    elif lang_name == "Tok Pisin" : return "tpi"
    elif lang_name == "Tokelau" : return "tkl"
    elif lang_name == "Tonga (Nyasa)" : return "tog"
    elif lang_name == "Tonga (Tonga Islands)" : return "ton"
    elif lang_name == "Tsimshian" : return "tsi"
    elif lang_name == "Tsonga": return "tso"
    elif lang_name == "Tswana": return "tsn"
    elif lang_name == "Tumbuka" : return "tum"
    elif lang_name == "Turkish" : return "tur"
    elif lang_name == "Turkish, Ottoman (1500-1928)": return "ota"
    elif lang_name == "Turkmen" : return "tuk"
    elif lang_name == "Tuvalu": return "tvl"
    elif lang_name == "Tuvinian": return "tyv"
    elif lang_name == "Twi" : return "twi"
    elif lang_name == "Ugaritic": return "uga"
    elif lang_name == "Uighur": return "uig"
    elif lang_name == "Ukrainian" : return "ukr"
    elif lang_name == "Umbundu" : return "umb"
    elif lang_name == "Undetermined": return "und"
    elif lang_name == "Urdu": return "urd"
    elif lang_name == "Uzbek" : return "uzb"
    elif lang_name == "Vai" : return "vai"
    elif lang_name == "Venda" : return "ven"
    elif lang_name == "Vietnamese": return "vie"
    elif lang_name == "Volapük" : return "vol"
    elif lang_name == "Votic" : return "vot"
    elif lang_name == "Wakashan languages": return "wak"
    elif lang_name == "Walamo": return "wal"
    elif lang_name == "Waray" : return "war"
    elif lang_name == "Washo" : return "was"
    elif lang_name == "Welsh" : return "wel"
    elif lang_name == "Welsh" : return "cym"
    elif lang_name == "Wolof" : return "wol"
    elif lang_name == "Xhosa" : return "xho"
    elif lang_name == "Yakut" : return "sah"
    elif lang_name == "Yao" : return "yao"
    elif lang_name == "Yapese": return "yap"
    elif lang_name == "Yiddish" : return "yid"
    elif lang_name == "Yoruba": return "yor"
    elif lang_name == "Yupik languages" : return "ypk"
    elif lang_name == "Zande" : return "znd"
    elif lang_name == "Zapotec" : return "zap"
    elif lang_name == "Zenaga": return "zen"
    elif lang_name == "Zhuang": return "zha"
    elif lang_name == "Zulu": return "zul"
    elif lang_name == "Zuni": return "zun"
    else: return "Undefined"